#!/bin/bash

STATUS_FULL=`acpi | cut -d " " -f3-5`
STATUS=`echo "$STATUS_FULL" | cut -d ',' -f 1`
PERCENT=`echo "$STATUS_FULL" | cut -d ',' -f 2`

if [ "$STATUS" == "Unknown" ]; then
	echo "&#xf128; $PERCENT"
fi

if [ "$STATUS" == "Full" ]; then
	echo "&#xf0e7;  Full$PERCENT"
fi

if [ "$STATUS" == "Charging" ]; then
	echo "&#xf1e6;  Charging$PERCENT"
fi

if [ "$STATUS" == "Discharging" ]; then
	echo "&#xf0e7;  Discharging$PERCENT"
fi
