#!/bin/bash

case $BLOCK_BUTTON in
	1) st -e nmtui ;;
	3) pgrep -x dunst >/dev/null && notify-send "🌐 Internet module:
	- Click for \`nmtui\` for wifi access
	: no wifi connection
	📶: wifi connection with quality
	❎: no ethernet
	🌐: ethernet working
	" ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiIcon=""

[ ! -n "${wifiIcon+var}" ] && wifiIcon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%" }')

printf "%s %s" "$wifiIcon" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"
